name: Android Emulator Tests
on:
  pull_request:
    branches:
      - main
      - beta
    paths-ignore:
      - '**.md'
      - 'website/**'
      - '**.yml'
jobs:
  test:
    name: Hardware-accelerated Android emulator test
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28, 29, 30, 31, 32, 33]
        target: [google_apis]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: 11
            distribution: corretto
            cache: 'gradle'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel_6
          script: ./gradlew connectedCheck