name: Unit tests application
on:
  fork:
    branches:
      - '**'
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
    paths-ignore:
      - 'website/**'
      - '**.yml'
  pull_request:
    branches:
      - main
      - beta
    paths-ignore:
      - '**.md'
      - 'website/**'
      - '**.yml'
jobs:
  unit_tests:
      name: Unit Tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Create file
          run: touch /home/runner/work/AutoNote/AutoNote/app/google-services.json | base64
        - name: Putting data
          env:
            DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
          run: echo $DATA > /home/runner/work/AutoNote/AutoNote/app/google-services.json
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: 11
            distribution: 'adopt'
            cache: 'gradle'
        - name: Set execution flag for gradlew
          run: chmod +x gradlew
        - name: Unit tests
          run: ./gradlew test
  # test:
  #   runs-on: macos-latest
  #   needs: unit_tests
  #   strategy:
  #     matrix:
  #       api-level: [28, 29, 30, 31, 32, 33]
  #       target: [google_apis]
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #     - name: Set execution flag for gradlew
  #       run: chmod +x gradlew
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v3
  #       with:
  #           java-version: 11
  #           distribution: 'adopt'
  #           cache: 'gradle'
  #     - name: run tests
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: ${{ matrix.api-level }}
  #         target: ${{ matrix.target }}
  #         arch: x86_64
  #         profile: pixel_6
  #         script: ./gradlew connectedCheck